CREATE TABLE IF NOT EXISTS game_task(
  id UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
  task_id UUID NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  image VARCHAR,
  selected_team UUID REFERENCES teams(id) ON DELETE CASCADE,
  completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE games ADD COLUMN started BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE games ADD COLUMN finished BOOLEAN NOT NULL DEFAULT FALSE;
